// Code generated by "stringer -type=Goal"; DO NOT EDIT.

package agent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[MoveAdjacentToTarget-1]
}

const _Goal_name = "NoneMoveAdjacentToTarget"

var _Goal_index = [...]uint8{0, 4, 24}

func (i Goal) String() string {
	if i >= Goal(len(_Goal_index)-1) {
		return "Goal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Goal_name[_Goal_index[i]:_Goal_index[i+1]]
}
