// Code generated by "stringer -type=Value"; DO NOT EDIT.

package kind

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Human-1]
	_ = x[Apple-2]
}

const _Value_name = "NoneHumanApple"

var _Value_index = [...]uint8{0, 4, 9, 14}

func (i Value) String() string {
	if i >= Value(len(_Value_index)-1) {
		return "Value(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Value_name[_Value_index[i]:_Value_index[i+1]]
}
